@extends('layouts.app')
@section('title')

@section('content')
<div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5">
          <section class="py-5">
          <!-- Post -->   
            <div class="row mb-4">            
              <div class="col-lg-12 mb-4 mb-lg-0">
                <div class="card">
                  <div class="card-header"  style="background-color: #f55b5b; color: #e8e5e5;">
                    <h3> {{ $myClass->class_name}} </h3>
                    <p>{{ $myClass->user_profile->given_name }} {{ $myClass->user_profile->family_name }} | {{ $myClass->subject->subject_desc}} | {{ $myClass->section->section_name}}</p> 
                  </div>
                  <div class="card-body" >
                    <div class=" text-center">

  <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->color(38, 38, 38, 0.85)->backgroundColor(255, 255, 255, 0.82)->size(300)->generate($qrcode->qrcode)) !!} " class="img-responsive">
  <p> You may now let the students to scan the QR Code!</p>

  <button type="submit" id="autogenerate_qr" class="btn btn-primary">Generate New</button>
</div>

                    </div>
                </div>
            </div>
         

 </div>
</section>
</div>
                        <script>
   //Delete Items
  $('#autogenerate_qr').click(function(){
      if(confirm('Are you sure you want to generate a new QR Code?')){

         $.ajax({
            type: "POST",
            cache: false,
            url : "{{}}",
            data: {action:'updateqr'},
                success: function(data) {
                  if (data==1) {
                   location.reload();
                 }else{
                  alert( 'Ups error :P ');
                 }
                }
            })

      
    }else{
        return false;
    }
  });
  //end qr autogenerated
</script>
@endsection
